#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyWorkoutPal.Resource", IsApplication=true)]

namespace MyWorkoutPal
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int account = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bar_chart_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int dumbbell_icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int edit_icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Intro = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int line_graph = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int PowerBuilderLauncher = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int signInButton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int signInButtonLight = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int signUpButton = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int toolbar_dropshadow = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int toolbar_upshadow_grey = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int white_button = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002b
			public const int CreatorLayout = 2131099691;
			
			// aapt resource value: 0x7f06002d
			public const int Exercise1 = 2131099693;
			
			// aapt resource value: 0x7f060022
			public const int LinearTest = 2131099682;
			
			// aapt resource value: 0x7f060035
			public const int PPLPPL = 2131099701;
			
			// aapt resource value: 0x7f060031
			public const int PostSetLayout = 2131099697;
			
			// aapt resource value: 0x7f06002e
			public const int PreSetLayout = 2131099694;
			
			// aapt resource value: 0x7f060011
			public const int appName = 2131099665;
			
			// aapt resource value: 0x7f060001
			public const int back = 2131099649;
			
			// aapt resource value: 0x7f06001e
			public const int btnAdd = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int btnEdit = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int btnRemove = 2131099680;
			
			// aapt resource value: 0x7f060034
			public const int create = 2131099700;
			
			// aapt resource value: 0x7f06000c
			public const int done = 2131099660;
			
			// aapt resource value: 0x7f06001d
			public const int dontUse = 2131099677;
			
			// aapt resource value: 0x7f06002a
			public const int edtDays = 2131099690;
			
			// aapt resource value: 0x7f06001c
			public const int edtEmail = 2131099676;
			
			// aapt resource value: 0x7f060019
			public const int edtName = 2131099673;
			
			// aapt resource value: 0x7f060029
			public const int edtPlanName = 2131099689;
			
			// aapt resource value: 0x7f06001b
			public const int edtReps = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int edtSets = 2131099674;
			
			// aapt resource value: 0x7f060009
			public const int female = 2131099657;
			
			// aapt resource value: 0x7f06002c
			public const int finished = 2131099692;
			
			// aapt resource value: 0x7f060017
			public const int forgot = 2131099671;
			
			// aapt resource value: 0x7f06000f
			public const int imagewrapper = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int intrologo = 2131099664;
			
			// aapt resource value: 0x7f060018
			public const int linearLayoutMain = 2131099672;
			
			// aapt resource value: 0x7f060021
			public const int listView = 2131099681;
			
			// aapt resource value: 0x7f06000e
			public const int login = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int male = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int myLinearLayout = 2131099651;
			
			// aapt resource value: 0x7f060023
			public const int my_awesome_taskbar = 2131099683;
			
			// aapt resource value: 0x7f060000
			public const int my_awesome_toolbar = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int namer = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int none = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int or = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int passworder = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int plot_view = 2131099652;
			
			// aapt resource value: 0x7f06002f
			public const int reps4 = 2131099695;
			
			// aapt resource value: 0x7f060032
			public const int reps5 = 2131099698;
			
			// aapt resource value: 0x7f060007
			public const int sex = 2131099655;
			
			// aapt resource value: 0x7f060012
			public const int signup = 2131099666;
			
			// aapt resource value: 0x7f060024
			public const int taskbar1 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int taskbar2 = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int taskbar3 = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int taskbar4 = 2131099687;
			
			// aapt resource value: 0x7f060002
			public const int toolbar_title = 2131099650;
			
			// aapt resource value: 0x7f060016
			public const int txtView_Email = 2131099670;
			
			// aapt resource value: 0x7f060013
			public const int txtView_Name = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int txtView_Reps = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int txtView_Sets = 2131099668;
			
			// aapt resource value: 0x7f060028
			public const int upshadow = 2131099688;
			
			// aapt resource value: 0x7f060030
			public const int weight4 = 2131099696;
			
			// aapt resource value: 0x7f060033
			public const int weight5 = 2131099699;
			
			// aapt resource value: 0x7f06000b
			public const int weighter = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChartLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int edit_profile_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Intro = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int list_view = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login_Content = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ProgramHomeLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PushViewerLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int WorkoutCreatorContent = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int WorkoutLayoutNew = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int WorkoutSelecterLayout = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int CustomActionBarTheme = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int LogInActionBar = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int LogInActionBarTheme = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int MyActionBar = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
